#!/bin/sh

echo $$

ulimit -v 4000000
ulimit -c unlimited

renice 10 -p $$

mkdir bin || ( rmdir bin && mkdir bin) || exit 1
mkdir lib || ( rmdir lib && mkdir lib) || exit 1
mkdir man || ( rmdir man && mkdir man) || exit 1
mkdir ruby || ( rmdir ruby && mkdir ruby) || exit 1
mkdir share || ( rmdir share && mkdir share) || exit 1
rmdir ruby

prefix=`pwd`
date
git clone https://github.com/ruby/ruby.git || exit 1
cd ruby &&
time autoconf &&
time ./configure --prefix="$prefix" --with-valgrind CPPFLAGS='-DRUBY_DEBUG_ENV' "$@" &&
time make &&
time make install &&
time make test &&
time make test-all TESTS='--hide-skip -v'
date

